### PR TITLE
Vue Query

### PR DESCRIPTION
**Pull request by SecretJ12**
This plugin should make the code more reusable and simpler, while providing buffering in order to reduce extensive reloading of the same data.

TODO replacement at:
- [ ] AssignMatch Group & Knockout
- [ ] View Group & Knockout
- [ ] Player registration

### CODE REVIEW

**Comment by FungOliver** [comment]
Is this supposed to be merged with the master branch?

**Comment by SecretJ12** [comment]
> Is this supposed to be merged with the master branch? It might be a bit hard to review xd

Wasnt my intention xD
But we could do it at some point soon

**Review by FungOliver — APPROVED** [review]
Looks good to me! 👍
I found two small mistakes, which I fixed, but otherwise I think this ready to be merged.

**Comment by hertelukas** [comment]
> > Is this supposed to be merged with the master branch? It might be a bit hard to review xd
> 
> Wasnt my intention xD But we could do it at some point soon

I think you should, so I can look at the insights and actually get some insights!

**Comment by SecretJ12** [comment]
> > > Is this supposed to be merged with the master branch? It might be a bit hard to review xd
> > 
> > Wasnt my intention xD But we could do it at some point soon
> 
> I think you should, so I can look at the insights and actually get some insights!

As we gonna merge it in sight, the insights will be available in sight. 🙃

**Pull request merged**
